version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app # source:destination
    command: python manage.py runserver 0.0.0.0:8000